# -*- coding: utf-8 -*-
"""AI study assis using 2LLM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VW7bhDYWcir4VkrOVrpmXLdGVjcorDpj
"""

# ============================================================
# LANGGRAPH DOCUMENT + WEB VERIFICATION PROJECT
# PDF → LLM 1 → WEB → LLM 2
# Google Colab | No API Key | No TTS
# ============================================================

# -----------------------------
# 1. INSTALL LIBRARIES
# -----------------------------
print("Installing required libraries...")

!pip install -q langgraph pypdf transformers accelerate ddgs

print("Libraries installed successfully!")


# -----------------------------
# 2. IMPORT LIBRARIES
# -----------------------------
from typing import TypedDict
from langgraph.graph import StateGraph, START, END
from pypdf import PdfReader
from transformers import pipeline
import torch
import re

print("Libraries imported successfully!")


# -----------------------------
# 3. UPLOAD PDF
# -----------------------------
from google.colab import files

print("\n========================================")
print("UPLOAD YOUR PDF")
print("========================================")

uploaded = files.upload()

pdf_filename = list(uploaded.keys())[0]

reader = PdfReader(pdf_filename)

document_text = ""

for page in reader.pages:
    text = page.extract_text()
    if text:
        document_text += text + "\n"

print("\nPDF loaded successfully!")
print("File:", pdf_filename)
print("Pages:", len(reader.pages))
print("Characters:", len(document_text))

print("\nDocument preview:")
print(document_text[:1500])


# -----------------------------
# 4. SPLIT DOCUMENT INTO CHUNKS
# -----------------------------
def create_chunks(text, chunk_size=2500, overlap=300):

    chunks = []

    start = 0

    while start < len(text):

        end = start + chunk_size

        chunk = text[start:end]

        if chunk.strip():
            chunks.append(chunk)

        start = end - overlap

    return chunks


chunks = create_chunks(document_text)

print("\nDocument chunks created:", len(chunks))


# -----------------------------
# 5. SIMPLE DOCUMENT RETRIEVAL
# -----------------------------
def retrieve_relevant_chunks(question, top_k=3):

    question_words = set(
        re.findall(r'\b[a-zA-Z]{3,}\b', question.lower())
    )

    scored_chunks = []

    for chunk in chunks:

        chunk_words = set(
            re.findall(r'\b[a-zA-Z]{3,}\b', chunk.lower())
        )

        score = len(question_words.intersection(chunk_words))

        scored_chunks.append((score, chunk))

    scored_chunks.sort(
        key=lambda x: x[0],
        reverse=True
    )

    return [
        chunk
        for score, chunk in scored_chunks[:top_k]
    ]


# -----------------------------
# 6. LOAD LLM
# -----------------------------
print("\n========================================")
print("LOADING LLM")
print("========================================")

device = 0 if torch.cuda.is_available() else -1

llm = pipeline(
    "text-generation",
    model="Qwen/Qwen2.5-0.5B-Instruct",
    device=device,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32
)

print("LLM loaded successfully!")

if torch.cuda.is_available():
    print("GPU detected:", torch.cuda.get_device_name(0))
else:
    print("Running on CPU")


# -----------------------------
# 7. LLM FUNCTION
# -----------------------------
def run_llm(prompt, max_new_tokens=350):

    messages = [
        {
            "role": "system",
            "content": "You are a helpful academic assistant. Give clear and factual answers."
        },
        {
            "role": "user",
            "content": prompt
        }
    ]

    output = llm(
        messages,
        max_new_tokens=max_new_tokens,
        do_sample=False
    )

    generated = output[0]["generated_text"]

    if isinstance(generated, list):
        return generated[-1]["content"]

    return generated


# -----------------------------
# 8. LANGGRAPH STATE
# -----------------------------
class VerificationState(TypedDict):

    document_text: str
    question: str

    retrieved_context: str

    llm1_answer: str

    web_results: str

    llm2_answer: str


# -----------------------------
# 9. LLM 1 NODE
# -----------------------------
def llm1_node(state):

    print("\n")
    print("========================================")
    print("STEP 1: LLM 1 - DOCUMENT ANALYSIS")
    print("========================================")

    question = state["question"]

    relevant_chunks = retrieve_relevant_chunks(
        question,
        top_k=3
    )

    context = "\n\n--- DOCUMENT SECTION ---\n\n".join(
        relevant_chunks
    )

    prompt = f"""
You are LLM 1 in a document verification system.

Use ONLY the document context below.

DOCUMENT CONTEXT:
{context}

QUESTION:
{question}

TASK:
Answer the question using the document.

Explain the answer clearly.
Mention the important points.
Do not invent information.

DOCUMENT-BASED ANSWER:
"""

    answer = run_llm(
        prompt,
        max_new_tokens=400
    )

    print("\nLLM 1 ANSWER:")
    print(answer)

    return {
        "retrieved_context": context,
        "llm1_answer": answer
    }


# -----------------------------
# 10. WEB SEARCH NODE
# -----------------------------
def web_search_node(state):

    print("\n")
    print("========================================")
    print("STEP 2: WEB SEARCH")
    print("========================================")

    question = state["question"]

    llm1_answer = state["llm1_answer"]

    # Create a short web query
    query = question

    print("Searching web for:")
    print(query)

    try:

        from ddgs import DDGS

        search_results = []

        with DDGS() as ddgs:

            results = ddgs.text(
                query,
                max_results=5
            )

            for result in results:

                title = result.get("title", "")
                body = result.get("body", "")
                href = result.get("href", "")

                search_results.append(
                    f"TITLE: {title}\n"
                    f"CONTENT: {body}\n"
                    f"SOURCE: {href}"
                )

        web_text = "\n\n--------------------\n\n".join(
            search_results
        )

        if not web_text:
            web_text = "No web results were found."

    except Exception as e:

        web_text = f"Web search failed: {str(e)}"

    print("\nWEB EVIDENCE:")
    print(web_text[:5000])

    return {
        "web_results": web_text
    }


# -----------------------------
# 11. LLM 2 VERIFICATION NODE
# -----------------------------
def llm2_node(state):

    print("\n")
    print("========================================")
    print("STEP 3: LLM 2 - VERIFICATION")
    print("========================================")

    question = state["question"]

    llm1_answer = state["llm1_answer"]

    web_results = state["web_results"]

    prompt = f"""
You are LLM 2, the final verification agent.

You must verify the answer produced by LLM 1 using the web evidence.

QUESTION:
{question}

--------------------------------
LLM 1 ANSWER
--------------------------------

{llm1_answer}

--------------------------------
WEB EVIDENCE
--------------------------------

{web_results}

--------------------------------
TASK
--------------------------------

Compare the LLM 1 answer with the web evidence.

Determine:

1. What information is supported?
2. What information is not supported?
3. Are there any contradictions?
4. What is the corrected final answer?

Use this format:

VERIFICATION STATUS:
Supported / Partially Supported / Conflicting / Insufficient Evidence

ANALYSIS:
Explain the comparison.

FINAL ANSWER:
Give the most accurate answer based on the document and web evidence.

IMPORTANT:
Do not blindly trust LLM 1.
Do not blindly trust the web.
If evidence is insufficient, clearly say so.
"""

    final_answer = run_llm(
        prompt,
        max_new_tokens=500
    )

    print("\nFINAL VERIFICATION:")
    print(final_answer)

    return {
        "llm2_answer": final_answer
    }


# -----------------------------
# 12. BUILD LANGGRAPH
# -----------------------------
print("\n")
print("========================================")
print("BUILDING LANGGRAPH")
print("========================================")

builder = StateGraph(VerificationState)

builder.add_node(
    "llm1",
    llm1_node
)

builder.add_node(
    "web_search",
    web_search_node
)

builder.add_node(
    "llm2",
    llm2_node
)

builder.add_edge(
    START,
    "llm1"
)

builder.add_edge(
    "llm1",
    "web_search"
)

builder.add_edge(
    "web_search",
    "llm2"
)

builder.add_edge(
    "llm2",
    END
)

graph = builder.compile()

print("LangGraph created successfully!")


# -----------------------------
# 13. ASK USER QUESTION
# -----------------------------
print("\n")
print("========================================")
print("READY!")
print("========================================")

print("""
Pipeline:

PDF
 ↓
Document Retrieval
 ↓
LLM 1
 ↓
Web Search
 ↓
LLM 2
 ↓
FINAL VERIFIED ANSWER
""")

question = input(
    "\nEnter your question about the PDF: "
)


# -----------------------------
# 14. RUN LANGGRAPH
# -----------------------------
initial_state = {
    "document_text": document_text,
    "question": question,
    "retrieved_context": "",
    "llm1_answer": "",
    "web_results": "",
    "llm2_answer": ""
}

print("\n")
print("========================================")
print("RUNNING LANGGRAPH")
print("========================================")

result = graph.invoke(
    initial_state
)


# -----------------------------
# 15. DISPLAY FINAL RESULT
# -----------------------------
print("\n\n")
print("################################################")
print("#              FINAL RESULT                    #")
print("################################################")

print("\nQUESTION:")
print(question)

print("\n\n========== LLM 1 DOCUMENT ANSWER ==========\n")
print(result["llm1_answer"])

print("\n\n========== WEB EVIDENCE ==========\n")
print(result["web_results"][:6000])

print("\n\n========== LLM 2 VERIFIED ANSWER ==========\n")
print(result["llm2_answer"])

print("\n")
print("################################################")
print("#          PIPELINE COMPLETED                 #")
print("################################################")